services:
  # Default configuration for services in this file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Makes classes in src/ available to be used as services
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Tag controllers as services with controller.service_arguments
  App\Controller\:
    resource: "../src/Controller"
    tags: ["controller.service_arguments"]
parameters:
  upload_directory: "%kernel.project_dir%/public/uploads"
