lexik_jwt_authentication:
  secret_key: "%kernel.project_dir%/config/jwt/private.pem"
  public_key: "%kernel.project_dir%/config/jwt/public.pem"
  pass_phrase: "%env(JWT_PASSPHRASE)%" # Ensure this is defined in your .env file
  token_ttl: 3600 # Token time-to-live in seconds
