nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
    allow_headers: ["Content-Type", "Authorization", "auth-token"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
    expose_headers: []
    max_age: 3600
  paths:
    "^/api/":
      origin_regex: false
      allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
      allow_headers: ["Content-Type", "Authorization", "auth-token"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
      max_age: 3600
