security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: apiToken

  firewalls:
    # Public access to register and login routes without any authentication
    public_api:
      pattern: ^/api/user/(register|login)
      security: false

    # Custom authenticator for API routes requiring authentication
    api:
      stateless: true
      custom_authenticators:
        - App\Security\ApiTokenAuthenticator

  access_control:
    # No authentication required for register and login routes
    - { path: ^/api/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    # Secure the rest of the /api routes, require ROLE_USER
    - { path: ^/api, roles: ROLE_USER }
